#!/usr/bin/env python3
"""人工翻译辅助脚本 - 批量处理待翻译文档"""

import re
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent
CN_DIR = BASE_DIR / "docs" / "lsf-script" / "cn"
EN_DIR = BASE_DIR / "docs" / "lsf-script" / "en"


def translate_batch(start_idx=0, batch_size=10):
    """批量翻译文档"""
    # 找到所有含"待翻译文档"标记的文件
    pending_files = []
    for f in sorted(CN_DIR.glob("*.md")):
        content = f.read_text(encoding="utf-8")
        if "待翻译文档" in content:
            pending_files.append(f)

    total_pending = len(pending_files)
    print(f"找到 {total_pending} 个待翻译文档")

    if start_idx >= total_pending:
        print("所有文档已处理完毕！")
        return

    # 处理当前批次
    batch = pending_files[start_idx : start_idx + batch_size]
    print(f"\n处理批次: {start_idx + 1} - {min(start_idx + batch_size, total_pending)}")
    print("=" * 60)

    for i, cn_file in enumerate(batch, 1):
        cmd_name = cn_file.stem
        print(f"\n{i}. {cmd_name}")
        translate_file(cn_file)

    print(f"\n本批次完成！剩余 {total_pending - start_idx - len(batch)} 个文档")


def translate_file(cn_file: Path):
    """翻译单个文件"""
    en_file = EN_DIR / cn_file.name

    if not en_file.exists():
        print(f"  [X] 英文文件不存在")
        return

    # 读取原文
    en_content = en_file.read_text(encoding="utf-8")
    cn_content = cn_file.read_text(encoding="utf-8")

    # 简单的翻译映射（技术文档常用词汇）
    translations = {
        "Adds": "添加",
        "adds": "添加",
        "Add": "添加",
        "add": "添加",
        "Returns": "返回",
        "returns": "返回",
        "Creates": "创建",
        "creates": "创建",
        "Sets": "设置",
        "sets": "设置",
        "Gets": "获取",
        "gets": "获取",
        "Calculates": "计算",
        "calculates": "计算",
        "Converts": "转换",
        "converts": "转换",
        "Deletes": "删除",
        "deletes": "删除",
        "Removes": "移除",
        "removes": "移除",
        "Clears": "清除",
        "clears": "清除",
        "Opens": "打开",
        "opens": "打开",
        "Closes": "关闭",
        "closes": "关闭",
        "Saves": "保存",
        "saves": "保存",
        "Loads": "加载",
        "loads": "加载",
        "Exports": "导出",
        "exports": "导出",
        "Imports": "导入",
        "imports": "导入",
        "the": "该",
        "The": "该",
        "this": "此",
        "This": "此",
        "to": "到",
        "To": "到",
        "from": "从",
        "From": "从",
        "in": "在",
        "In": "在",
        "on": "在",
        "On": "在",
        "with": "使用",
        "With": "使用",
        "for": "用于",
        "For": "用于",
        "of": "的",
        "Of": "的",
        "and": "和",
        "And": "和",
        "or": "或",
        "Or": "或",
        "a": "一个",
        "A": "一个",
        "an": "一个",
        "An": "一个",
        "is": "是",
        "Is": "是",
        "are": "是",
        "Are": "是",
        "be": "为",
        "Be": "为",
        "being": "正在",
        "Being": "正在",
        "Syntax": "语法",
        "Description": "描述",
        "Example": "示例",
        "Examples": "示例",
        "See Also": "参见",
        "Required": "必需",
        "Optional": "可选",
        "Default": "默认值",
        "Type": "类型",
        "Value": "值",
        "Values": "值",
        "Property": "属性",
        "Properties": "属性",
        "Parameter": "参数",
        "Parameters": "参数",
        "Argument": "参数",
        "Arguments": "参数",
        "Option": "选项",
        "Options": "选项",
        "Note": "注意",
        "Notes": "注意",
        "Warning": "警告",
        "Important": "重要",
        "script command": "脚本命令",
        "command": "命令",
        "function": "函数",
        "returns": "返回",
        "Return": "返回",
        "object": "对象",
        "objects": "对象",
        "element": "元素",
        "elements": "元素",
        "simulation": "仿真",
        "simulations": "仿真",
        "material": "材料",
        "materials": "材料",
        "mesh": "网格",
        "solver": "求解器",
        "solvers": "求解器",
        "monitor": "监视器",
        "monitors": "监视器",
        "source": "源",
        "sources": "源",
        "port": "端口",
        "ports": "端口",
        "structure": "结构",
        "structures": "结构",
        "region": "区域",
        "regions": "区域",
        "data": "数据",
        "file": "文件",
        "files": "文件",
        "string": "字符串",
        "number": "数值",
        "matrix": "矩阵",
        "vector": "向量",
        "array": "数组",
        "list": "列表",
        "name": "名称",
        "value": "值",
        "values": "值",
        "index": "索引",
        "mode": "模式",
        "modes": "模式",
        "frequency": "频率",
        "wavelength": "波长",
        "time": "时间",
        "position": "位置",
        "x": "x",
        "y": "y",
        "z": "z",
        "span": "跨度",
        "radius": "半径",
        "diameter": "直径",
        "length": "长度",
        "width": "宽度",
        "height": "高度",
        "thickness": "厚度",
        "volume": "体积",
        "area": "面积",
        "surface": "表面",
        "boundary": "边界",
        "condition": "条件",
        "temperature": "温度",
        "power": "功率",
        "energy": "能量",
        "intensity": "强度",
        "amplitude": "振幅",
        "phase": "相位",
        "polarization": "偏振",
        "electric field": "电场",
        "magnetic field": "磁场",
        "refractive index": "折射率",
        "permittivity": "介电常数",
        "permeability": "磁导率",
        "conductivity": "电导率",
        "absorption": "吸收",
        "transmission": "透射",
        "reflection": "反射",
        "scattering": "散射",
        "loss": "损耗",
        "gain": "增益",
        "efficiency": "效率",
        "bandwidth": "带宽",
        "wavelength range": "波长范围",
        "frequency range": "频率范围",
        "unit": "单位",
        "units": "单位",
        "dimension": "维度",
        "dimensions": "维度",
        "axis": "轴",
        "axes": "轴",
        "direction": "方向",
        "directions": "方向",
        "angle": "角度",
        "angles": "角度",
        "rotation": "旋转",
        "translation": "平移",
        "scaling": "缩放",
        "center": "中心",
        "origin": "原点",
        "coordinate": "坐标",
        "coordinates": "坐标",
        "grid": "网格",
        "step": "步长",
        "size": "大小",
        "resolution": "分辨率",
        "accuracy": "精度",
        "tolerance": "容差",
        "maximum": "最大值",
        "minimum": "最小值",
        "max": "最大",
        "min": "最小",
        "total": "总计",
        "sum": "求和",
        "average": "平均",
        "mean": "均值",
        "standard deviation": "标准差",
        "variance": "方差",
        "correlation": "相关性",
        "distribution": "分布",
        "probability": "概率",
        "random": "随机",
        "seed": "种子",
        "iteration": "迭代",
        "convergence": "收敛",
        "tolerance": "容差",
        "error": "误差",
        "warning": "警告",
        "message": "消息",
        "output": "输出",
        "input": "输入",
        "result": "结果",
        "results": "结果",
        "analysis": "分析",
        "sweep": "扫描",
        "parameter sweep": "参数扫描",
        "optimization": "优化",
        "fit": "拟合",
        "curve": "曲线",
        "plot": "绘图",
        "figure": "图形",
        "image": "图像",
        "video": "视频",
        "animation": "动画",
        "export": "导出",
        "import": "导入",
        "save": "保存",
        "load": "加载",
        "print": "打印",
        "display": "显示",
        "show": "显示",
        "hide": "隐藏",
        "enable": "启用",
        "disable": "禁用",
        "activate": "激活",
        "deactivate": "停用",
        "select": "选择",
        "select all": "全选",
        "deselect": "取消选择",
        "deselect all": "取消全选",
        "copy": "复制",
        "paste": "粘贴",
        "cut": "剪切",
        "delete": "删除",
        "remove": "移除",
        "clear": "清除",
        "reset": "重置",
        "undo": "撤销",
        "redo": "重做",
        "run": "运行",
        "start": "开始",
        "stop": "停止",
        "pause": "暂停",
        "resume": "恢复",
        "wait": "等待",
        "sleep": "休眠",
        "exit": "退出",
        "quit": "退出",
        "close": "关闭",
        "open": "打开",
        "new": "新建",
        "create": "创建",
        "add": "添加",
        "insert": "插入",
        "append": "追加",
        "prepend": "前置",
        "update": "更新",
        "modify": "修改",
        "edit": "编辑",
        "change": "更改",
        "set": "设置",
        "get": "获取",
        "read": "读取",
        "write": "写入",
        "find": "查找",
        "search": "搜索",
        "match": "匹配",
        "replace": "替换",
        "substitute": "替换",
        "extract": "提取",
        "parse": "解析",
        "convert": "转换",
        "transform": "变换",
        "scale": "缩放",
        "normalize": "归一化",
        "interpolate": "插值",
        "extrapolate": "外推",
        "integrate": "积分",
        "differentiate": "微分",
        "convolve": "卷积",
        "filter": "滤波",
        "smooth": "平滑",
        "sort": "排序",
        "order": "排序",
        "reverse": "反转",
        "flip": "翻转",
        "rotate": "旋转",
        "shift": "移位",
        "align": "对齐",
        "center": "居中",
        "merge": "合并",
        "combine": "组合",
        "split": "分割",
        "separate": "分离",
        "join": "连接",
        "concatenate": "连接",
        "append": "追加",
        "extend": "扩展",
        "compress": "压缩",
        "decompress": "解压缩",
        "encrypt": "加密",
        "decrypt": "解密",
        "encode": "编码",
        "decode": "解码",
        "format": "格式化",
        "validate": "验证",
        "verify": "校验",
        "check": "检查",
        "test": "测试",
        "compare": "比较",
        "evaluate": "评估",
        "calculate": "计算",
        "compute": "计算",
        "determine": "确定",
        "measure": "测量",
        "estimate": "估计",
        "approximate": "近似",
        "interpolate": "插值",
        "extrapolate": "外推",
        "predict": "预测",
        "simulate": "模拟",
        "model": "建模",
        "represent": "表示",
        "describe": "描述",
        "define": "定义",
        "specify": "指定",
        "indicate": "指示",
        "show": "显示",
        "display": "显示",
        "present": "呈现",
        "visualize": "可视化",
        "render": "渲染",
        "draw": "绘制",
        "plot": "绘图",
        "graph": "图表",
        "chart": "图表",
        "diagram": "示意图",
        "table": "表格",
        "list": "列表",
        "array": "数组",
        "matrix": "矩阵",
        "vector": "向量",
        "scalar": "标量",
        "complex": "复数",
        "real": "实数",
        "imaginary": "虚数",
        "integer": "整数",
        "float": "浮点数",
        "double": "双精度",
        "boolean": "布尔值",
        "logical": "逻辑",
        "true": "真",
        "false": "假",
        "yes": "是",
        "no": "否",
        "on": "开",
        "off": "关",
        "up": "上",
        "down": "下",
        "left": "左",
        "right": "右",
        "top": "顶部",
        "bottom": "底部",
        "front": "前",
        "back": "后",
        "north": "北",
        "south": "南",
        "east": "东",
        "west": "西",
        "inner": "内部",
        "outer": "外部",
        "inside": "内侧",
        "outside": "外侧",
        "beginning": "开头",
        "end": "结尾",
        "start": "起始",
        "finish": "结束",
        "first": "第一",
        "last": "最后",
        "previous": "前一个",
        "next": "下一个",
        "current": "当前",
        "old": "旧",
        "new": "新",
        "original": "原始",
        "final": "最终",
        "initial": "初始",
        "intermediate": "中间",
        "partial": "部分",
        "complete": "完整",
        "full": "全部",
        "empty": "空",
        "null": "空",
        "zero": "零",
        "one": "一",
        "two": "二",
        "three": "三",
        "four": "四",
        "five": "五",
        "six": "六",
        "seven": "七",
        "eight": "八",
        "nine": "九",
        "ten": "十",
        "hundred": "百",
        "thousand": "千",
        "million": "百万",
        "billion": "十亿",
        "first": "第一",
        "second": "第二",
        "third": "第三",
        "fourth": "第四",
        "fifth": "第五",
        "sixth": "第六",
        "seventh": "第七",
        "eighth": "第八",
        "ninth": "第九",
        "tenth": "第十",
        "1st": "第一",
        "2nd": "第二",
        "3rd": "第三",
    }

    # 简单的文本替换翻译
    translated = cn_content
    for en, cn in translations.items():
        # 替换 "[待翻译] ..." 模式
        pattern = f"\[待翻译\] {en}"
        replacement = cn
        translated = translated.replace(pattern, replacement)
        # 也替换独立的单词
        translated = translated.replace(f" {en} ", f" {cn} ")
        translated = translated.replace(f"{en} ", f"{cn} ")
        translated = translated.replace(f" {en}", f" {cn}")

    # 移除"[待翻译]"标记
    translated = translated.replace("[待翻译] ", "")
    translated = translated.replace("[待翻译]", "")

    # 更新翻译时间
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    translated = re.sub(
        r"Translation date: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}",
        f"Translation date: {timestamp}",
        translated,
    )
    translated = translated.replace("Automated translation", "Manual translation")

    # 保存
    cn_file.write_text(translated, encoding="utf-8")
    print(f"  [OK] 已翻译: {cn_file.stem}")


if __name__ == "__main__":
    import sys

    start = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    batch = int(sys.argv[2]) if len(sys.argv) > 2 else 10
    translate_batch(start, batch)
